name: 'pull-digest'
description: 'Slack bot to get a simple digest of open PRs (ideal for standups)'

docs:
  - { title: 'README', url: 'https://github.com/leemachin/pull-digest/blob/master/README.md' }
